### ISSUE TITLE
Doesn't work with slackclient 1.0.5

### ISSUE THREAD

**Issue by stacecom** [jarshwah/slack-regex-responder#3] opened 2017-03-27 02:38 UTC
I was migrating this to a new server, and it looks like updates to slackclient cause it to fail, producing this error:

`2017-03-27 02:19:05.475267 - ERROR - Uh oh, couldn't determine bot user id from username: botname`

It gets `botname` right, but bails on failing to get the ID.  I downgraded slackclient on this server to 1.0.2 (the same version the previous server was running), and now it successfully connects.

**Comment by jarshwah** [comment] 2017-06-23 14:16
Sorry @stacecom my notifications are a mess, I'm trying to organise them a bit better.

I'm guessing https://github.com/slackapi/python-slackclient/pull/156/files is probably the cause of this issue. I don't actually have this service running anymore, but I'll try and figure it out. Open to pull requests too if you'd like to give it a crack?

**Comment by jarshwah** [comment] 2017-06-23 23:40
Fixed in https://github.com/jarshwah/slack-pattern-responder/commit/b517a368de7d9394c0561e4533ddb300767bdcec

Deployed new version 1.1.0: https://pypi.org/project/slack_responder/

**Closed as completed by jarshwah** 2017-06-23 23:40 UTC

**Comment by stacecom** [comment] 2017-06-24 18:31
That's great, thanks!
